- src: geerlingguy.pip
  version: 1.3.0
  name: pip
- src: geerlingguy.docker
  version: 2.5.2
  name: docker
- src: geerlingguy.repo-epel
  version: 1.2.3
  name: epel-repository
- src: retr0h.logrotate
  version: 2.0.1
  name: logrotate
- src: andrewrothstein.sudoers
  version: v1.0.9
  name: sudoers
- src: geerlingguy.java
  version: 1.9.5
  name: java
- src: nolte.minecraft
  version: v5.0.2
  name: minecraft
